- create-pull-request.py
As outline in #29, using a scheduled workflow breaks this Action with 
```
Traceback (most recent call last):
File "/create-pull-request.py", line 119, in <module>
if not ignore_event(github_event):
File "/create-pull-request.py", line 23, in ignore_event
deleted = "{deleted}".format(**github_event)
KeyError: 'deleted'
##[error]Docker run failed with exit code 1
```
The issue seems to be related to the fact, that on scheduled jobs the `$GITHUB_EVENT_PATH` file contains just one attribute 
```json
{
"schedule": "* * * * *"
}
```
whereas on `push` it contains a proper GitHub payload with `repository` and `sender` details.
I'm not really experienced with Python to provide a proper bug fix, but maybe @peter-evans can help me landing this fix. From what I can tell it's this [ignore_event …
> Do not break Action when using schedule jobs

- README.md
- create-pull-request.py
During testing, I found it useful to have this function skipped so I added a simple check for `SKIP_IGNORE` env variable. If present, the `ignore_event` function auto passes. This shouldn't have any impact on current workloads (unless `SKIP_IGNORE` is being populated and used in the same job step inadvertently).
> Add skip_ignore arg to ignore_event function

- .github/workflows/cpr-example-command.yml
- README.md
- action.yml
- dist/cpr/create_or_update_pull_request.py
- dist/cpr/create_pull_request.py
- dist/index.js
- docs/concepts-guidelines.md
- src/cpr/create_or_update_pull_request.py
- src/cpr/create_pull_request.py
- src/index.js
This PR adds a new parameter `repository` that let you customize the repository used for PR
use case:
- configure git to push to the fork
- create a PR between the repo (where github action run) and the fork
Fixes #143
usage:
```yaml
- name: Checkout code
uses: actions/checkout@v2
with:
ref: master
token: ${{ secrets.BOT_GITHUB_TOKEN }} # PAT with access to "my-user/fork". It will be needed when create-pull-request will push code
- name: Switch remote to fork via SSH
run: |
git remote set-url origin https://github.com/my-user/fork.git
git fetch --unshallow -p origin
- name: Create Pull Request
uses: peter-evans/create-pull-request@v2
with:
token: ${{ secrets.BOT_GITHUB_TOKEN }} # PAT needed to open PR accross fork
repository: my-companiy/original # base repository of PR
```
> Allow custom repository when pushin in fork

- .github/workflows/cpr-example-command.yml
- README.md
- action.yml
- dist/cpr/create_or_update_pull_request.py
- dist/cpr/create_pull_request.py
- dist/index.js
- docs/concepts-guidelines.md
- src/cpr/create_or_update_pull_request.py
- src/cpr/create_pull_request.py
- src/index.js
- Adds the `request-to-parent` input. This allows the creation of pull requests in the parent repository of a checked out fork. See the documentation for [push pull request branches to a fork](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork).
> Create pull requests in the parent repository of a checked out fork

- README.md
- __test__/create-or-update-branch.int.test.ts
- action.yml
- src/create-or-update-branch.ts
- src/create-pull-request.ts
- src/main.ts
This PR adds the ability to signoff the automatically created commits to enable DCO requirements for pull requests.
It adds the option `signoff` and the flag `-s` to `git commit` which adds "Signed-off-by: author < email >" with the value of `commiter` to the commit message.
Test cases for the new option are not included.
> Adds option to signoff commits

- dist/index.js
- src/create-or-update-branch.ts
- src/git-command-manager.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/626
> perf: set diff quiet and switch isdirty command order

- dist/index.js
- src/github-helper.ts
- src/utils.ts
* only minimal changes are needed to support GitHub Enterprise with this action
* use `GITHUB_SERVER_URL` and `GITHUB_API_URL` in all places that have been github.com specific before
* successfully tested with GitHub Enterprise Server 2.22
> Support GitHub Enterprise Server

- README.md
- dist/index.js
- src/create-or-update-branch.ts
- src/create-pull-request.ts
Fixes: https://github.com/peter-evans/create-pull-request/issues/974
> feat: add output for head sha

- README.md
- docs/concepts-guidelines.md
I encountered the same issue raised in #155 with a GitHub App. However, was able to get things to work by allowing read only access to Members to the GitHub App. Updating the docs!
> docs: Update to include app permissions needed to add teams as reviewers

- README.md
Use a logo builtin to shields.io / https://simpleicons.org/
The code is much shorter and simpler.
Also the icon is sharper :)
> docs: update marketplace logo

- .gitignore
- README.md
- action.yml
- dist/index.js
- src/create-or-update-branch.ts
- src/create-pull-request.ts
- src/main.ts
Add argument `add-pattern-array` to commit file with patterns. All other files will be cleaned.
Usage:
```yml
- name: Create Pull Request
uses: tutu-ru-mobile/create-pull-request@tutu  # Off course here will changed to peter-evans/...
with:
add-pattern-array: |
**.txt
**some/dirs**.png
token: ${{ secrets.GITHUB_TOKEN }}
```
Working sample:
https://github.com/avdim/test_pull_request_creation/blob/main/.github/workflows/blank.yml
Also need to fix README.md, because in version @v3 this argument not exists. I put @main branch in README.md
What do you think about this PR ?
> Add argument add-pattern-array

- dist/index.js
- src/git-command-manager.ts
Hi, thank you for developing this tool!
I found it causes an error when there are a branch and a path with the same name.
As explained [here](https://github.com/git/git/commit/a047fafc7866cc4087201e284dc1f53e8f9a32d5), adding `--` can fix this problem.
I've tested this here.
Before: https://github.com/kenji-miyake/autoware-github-actions/pull/11
After: https://github.com/kenji-miyake/autoware-github-actions/pull/12
I came up with using `git switch` as another option, but I refrained from that because it could be a big change.
> fix: add '--' to checkout command to avoid ambiguity

- README.md
- action.yml
The github pull request update API does not accept changing
draft status - the only way to do it appears to be through
the web UI.
> Document that draft status changes are not reflected

- README.md
Makes it easier to find and more clear. Reaction to my own comment at https://github.com/peter-evans/create-pull-request/issues/809#issuecomment-1061908603 .
> README.md: Add word "permissions" to part on GITHUB_TOKEN

- README.md
Just an idea for consideration :beers:
> README.md: Skip follow-up steps if there is no pull request

- dist/index.js
- src/github-helper.ts
Fixes: https://github.com/peter-evans/create-pull-request/issues/1163
Fixes an issue that occurs when a pull request is created from a repository fork that has been renamed from its original name.
> fix: use full name for head branch to allow for repo renaming

- docs/concepts-guidelines.md
Stumbled upon this when reading the documentation. The current quote and reference link appear to be out of date.
> Update GA quote/ref in concepts-guidelines.md

- __test__/integration-tests.sh
- dist/index.js
- package-lock.json
- package.json
- src/github-helper.ts
fixes: https://github.com/peter-evans/create-pull-request/issues/1176
> fix: avoid issue with case sensitivity of repo names

- dist/index.js
- src/create-or-update-branch.ts
Dockerized self-hosted runner (https://github.com/myoung34/docker-github-actions-runner) does not reset its local storage when a task is finished.
Thus, a newly created PR via worker#5 cannot be fetched via worker#7 because its not a fast-forward change.
This makes the later `hasDiff` logic that stops pushing if the actual content has no difference (the commit hashes are different because the commit has different `createdAt` timestamp.
[PR Log]
[Action Log]
[Actual diff between two consequent pushes]
Adding force option to git.fetch will overwrite previously cached branch information.
I found that all four `git.fetch` command in `create-or-update-branch.ts` already has the `force` option except the one changed in this PR.
I may add manual `rm -rf /working/.git` command before all …
> feat: add `force` option to `tryFetch`

- src/octokit-client.ts
In our case we have self hosted runners which are managed by our enterprise. All the proxy envvars are set in the runners itself. 
And we would need the proxy if we would go to [github.com](https://github.com) but not if we use this action to create a PR in our self hosted github enterprise. 
This change will check the environment variable `no_proxy` and will only use proxy agent if the requested url is not part of this variable. Currently this only works without wildcards in the domains which are part of `no_proxy`.
Let me know if something like this is out of scope or if there should be further changes.
> Support no_proxy environment variable

- dist/index.js
- src/create-or-update-branch.ts
- src/git-command-manager.ts
Fixes: https://github.com/peter-evans/create-pull-request/issues/1202
> fix: handle nothing to commit when autocrlf is set

- __test__/utils.unit.test.ts
- dist/index.js
- src/utils.ts
By escaping the `.` in the regex.
I think the bug got introduced by https://github.com/peter-evans/create-pull-request/pull/1153
Fixes #1256
> fix: only strip optional '.git' suffix from https server remote name and not 'Xgit'

- __test__/create-or-update-branch.int.test.ts
- dist/index.js
- src/create-or-update-branch.ts
fixes: https://github.com/peter-evans/create-pull-request/issues/1191
> fix: handle update after force pushing base to a new commit

- __test__/utils.unit.test.ts
- dist/index.js
- src/create-pull-request.ts
- src/utils.ts
Follows https://github.com/peter-evans/create-pull-request/pull/1315
> fix: support github server url for pushing to fork

- dist/index.js
- src/create-pull-request.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/1321
> fix: add check for missing token input

- .github/workflows/ci.yml
- .github/workflows/cpr-example-command.yml
- README.md
- action.yml
The noreply email address for GitHub accounts since July 18, 2017, contain an ID number and the username in the form of [ID+USERNAME@users.noreply.github.com](mailto:ID+USERNAME@users.noreply.github.com) (the documentation on it is [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)).
When any action happens in a workflow, it happens in the name of the the [github-actions[bot]](https://api.github.com/users/github-actions%5Bbot%5D) user, which was created on 2018-07-30T09:30:16Z, a year after they started using their new format.
This PR should incorporate both of these changes, and unify the behaviour.
> Update github-actions[bot] and author email format

- src/create-pull-request.ts
- src/github-helper.ts
> RFC: allow `push-to-fork` to push to sibling repos

- .github/workflows/ci.yml
- action.yml
Similar to #1074 but this time upgrading the Node.js runtime from v16 to v20. Note that Node.js v16 will be end of life on 11 Sep 2023, so GitHub will probably deprecate it around that time for Actions as well.
It might make sense to combine this upgrade with a bump from `actions/checkout@v3` to `actions/checkout@v4` because it also bumped the Node.js runtime from v16 to v20. Other actions (relevant: `peter-evans/create-or-update-project-card`, `actions/setup-node`, `actions/upload-artifact`, `actions/download-artifact`, `peter-evans/find-comment`, `peter-evans/create-or-update-comment`, `peter-evans/slash-command-dispatch`, `actions/setup-java`[^1], `peter-evans/repository-dispatch`) used/mentioned here do not seem be upgraded yet, except for …
> Update action runtime to node 20

- README.md
https://github.com/actions/checkout/releases/tag/v4.1.1
checkout v4 is already released, so if there's no specific reason we should use that.
> Use checkout v4

- README.md
https://github.com/peter-evans/create-pull-request/issues/1520
> Note about `delete-branch`

- dist/index.js
- src/github-helper.ts
fixes https://github.com/peter-evans/create-pull-request/issues/2790
> fix: list pulls using the correct head format

- dist/index.js
- src/create-or-update-branch.ts
This works for me locally, but I am not sure of the total implications to other use-cases. I explicitly didn't update the push to fork use-case when mentioned it's not supported.
For me, it went from 18+ minutes -> 7s. YMMV
Fixes https://github.com/peter-evans/create-pull-request/issues/2809
> Update git.fetch calls to use depth=1

- __test__/create-or-update-branch.int.test.ts
- dist/index.js
- src/create-or-update-branch.ts
Follows https://github.com/peter-evans/create-pull-request/pull/2810
Fixes https://github.com/peter-evans/create-pull-request/issues/2809
> perf: shallow fetch the actual base when rebasing from working base

- dist/index.js
- src/create-or-update-branch.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/2847
> fix: drop unnecessary fetch with unshallow on push-to-fork

- __test__/create-or-update-branch.int.test.ts
- dist/index.js
- src/create-or-update-branch.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/2847
> perf: limit the fetch depth of pr branch

- dist/index.js
- package-lock.json
- package.json
- src/octokit-client.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/2764
> fix: update proxy support to follow octokit change to fetch api

- README.md
- action.yml
- dist/index.js
- src/create-pull-request.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/2969
> feat: add branch name output

- README.md
- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/create-pull-request.ts
- src/git-command-manager.ts
- src/main.ts
Add support for automatically signing the commits as `github-actions` bot. This is useful in cases where repo/org owners have enforced a signed-commit policy. If a custom github-token is provided for another Github App, then the commit will be signed as that app.
This PR is related to or addresses the following issues:
- #1936 
- #1607 
- #1241 
- #1162
- #1055 
- #708 
I am a newbie with Typescript, so I have not separated out the logic to a different file or broken it into smaller functions/utilities. I might be able to spend a little bit more time on it to implement suggestions, but if it requires major refactoring, then please feel free to refactor and push the commits directly (or can also merge this PR and then refactor separately in a new PR).
> Add support for signed commits

- dist/index.js
- src/create-or-update-branch.ts
Towards https://github.com/peter-evans/create-pull-request/issues/3311
> fix: handle ambiguous argument failure on diff stat

- docs/concepts-guidelines.md
The option suggested here (Read only) is not an option, and wouldn't mean/do anything - you can read these files if you have access to the repo files. The description says this is needed if the PR could change the workflow files, so you need "Read and Write". Pretty sure this is just a typo, copied from the line below instead of the line above.
Someone else notices this, and I just did too.
> docs: correct suggestion for bot setup

- __test__/create-or-update-branch.int.test.ts
- __test__/git-command-manager.int.test.ts
- dist/index.js
- src/git-command-manager.ts
- src/github-helper.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/3353
> fix: support submodules when commit signing

- package-lock.json
- package.json
- src/octokit-client.ts
`undici` is already provided by Node.js, so we don't need to bundle our own version of it. Use the `node-native-fetch` library, which takes care of this and has battle-tested proxy-handling code.
before:
2107kB  dist/index.js
62484 lines
after:
1812kB  dist/index.js
36063 lines
> chore: don't bundle undici

- docs/concepts-guidelines.md
Closes https://github.com/peter-evans/create-pull-request/issues/3510
Even if the scenario I hit this with is fairly specific, we know that if nothing else, at least _this_ action is in `.github/workflows` somewhere, and the issue is possible if not likely to trigger in all setups when they update this action's version in it.
> docs: note `push-to-repo` classic PAT `workflow` scope requirement

- README.md
I was confused by the README, because it mentioned _updating an existing branch_, but not updating an existing _pull request_. Obviously, it doesn't make sense for the action to create a new PR even if there is an existing open PR, but I figure it's better to be explicit upfront in the README.
> docs(README): clarify that an existing open PR is managed

- __test__/entrypoint.sh
- __test__/git-command-manager.int.test.ts
- dist/index.js
- src/git-command-manager.ts
Fixes https://github.com/peter-evans/create-pull-request/issues/3577
> fix: preserve unicode in filepaths when commit signing

- docs/examples.md
Closes #3624
This PR adds a workflow tip to the examples document. The example uses the `notice` workflow command to show a created pull request info.
Please feel free to give me feedback!
> docs: add workflow tip for showing message via workflow command

- dist/index.js
- src/git-command-manager.ts
Towards https://github.com/peter-evans/create-pull-request/issues/3750
> fix: suppress output for some git operations

- docs/concepts-guidelines.md
The current description of `on: ready_for_review` may confuse readers because a workflow with `ready_for_review` should be written as below:
```yaml
on:
pull_request:
types: [ready_for_review]
```
- `pull_request` is an event
- `ready_for_review` is an event type of `pull_request`
Refs:
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onevent_nametypes
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
> docs: fix workaround description about `ready_for_review`

- README.md
Updated docs for `add-paths` param. Moved some content into the previously empty "Default" column, to elucidate default behavior.
> Docs: `add-paths` default behavior
